name: Test and release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-release:
    uses: zifeo/workflows/.github/workflows/py-test-release.yml@main
    with:
      python-matrix: '["3.8", "3.9", "3.10"]'
      poetry-version: "1.1.12"
      poetry-install-extra-args: "--extras all"
      python-version: "3.10"
      docker-compose: true
      docker-build: true
      publish-docker: true
      publish-pypi: true
    secrets:
      pypi-token: ${{ secrets.PYPI_TOKEN }}

